### ISSUE TITLE
Getting in contact

### ISSUE THREAD

**Issue by schancel** [opencap/protocol#57]
Hello,  

I really like what you're doing here.  I'd like to contribute if possible, and wanted to talk about some functionality I'd like to see regarding secure messaging as part of the spec.  I could help add it if the concept is appreciated.

**Comment by schancel** [comment]
A group of people were corresponding on a similar spec.  We'd like to help out with what you're doing instead.  If you have telegram, here's a link: https://t.me/joinchat/HCYr50adBu4RnHDQoZNUIg

**Comment by lane-c-wagner** [comment]
Sorry, heres one that should work: https://discord.gg/FTMCBE8

Ill join that telegram as well
