### ISSUE TITLE
IDN homograph attack

### ISSUE THREAD

**Issue by michelf** [opencap/protocol#58]
Maybe you should add a note about [international domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) in the alias. Those are the domain names with non-ASCII characters that results in a [Punycode](https://en.wikipedia.org/wiki/Punycode) ASCII name when doing the actual DNS request. Are they supported? If they are, you need to protect against [the homograph attack](https://en.wikipedia.org/wiki/IDN_homograph_attack#Homographs_in_internationalized_domain_names). The easiest way to mitigate is to disallow non-ASCII in the domain name part of the alias.

**Comment by lane-c-wagner** [comment]
Thanks! Sorry I just saw this, got it addressed.
