### ISSUE TITLE
duplicate coin tickers

### ISSUE THREAD

**Issue by ThatBrianDude** [opencap/protocol#6]
As I was building a cc index for myself I realized that there are multiple currencies out there with identical ticker names. I found that there is no centralized database in which cc core teams may register their ticker to avoid duplicates. This will cause restrictions for users across two currencies that share a ticker even though the preferred alias belongs to a different currency. An example: ArcticCoin is an altcoin (currency) and Arcade is a Ethereum Token (asset). Both share the same ticker "ARC". I came across about 15 other duplicates. 

A possible solution would be to maintain a record in which each currency gets a truly unique ID which can either be voted upon, automatically generated or agreed upon with the core team.

**Comment by ThatBrianDude** [comment]
We may not forget to mention this in the endpoint documentation as say when two of these currencies are supported they'd both require a uid which wouldn't be known to a developer using ccap and one of those currencies. Perhaps there should be a descriptive error message when specifying one of the known duplicates inside the ticker list file in an http request.

**Comment by danhalliday** [comment]
This is a thorny problem all over crypto software right now. I wonder if the domain name system is your best tool here, just as with the aliases themselves.

Could you create full unique identifiers for all coins, namespaced by their project domains? I could imagine a nice clean list like that being picked up by and used by lots of other projects too and being a good single source of truth. It also does away with any argument over guardianship of coins — you’re just referring to a specific fork of a coin.

So perhaps you’d use something like:

    Bitcoin
    org.bitcoin.BTC

    Nano
    org.nano.NANO

    XRP
    com.ripple.XRP

See reverse domain name syntax: https://en.m.wikipedia.org/wiki/Reverse_domain_name_notation and uniform type identifiers: https://en.m.wikipedia.org/wiki/Uniform_Type_Identifier for an idea of how these concepts have been put into widespread use for many years.

**Comment by shilch** [comment]
Let's just use an unsigned 16 bit integer (can still be extended later with varints) and an agreed index on which coin/chain/address type maps to which identifier. Note the use of the word 'address type' as there are some cryptocurrencies that have multiple address types with different purposes, e.g. Zcash has t-addresses and z-addresses, or Lisk has addresses and delegate names. A user might want to specify one of these addresses or both.  
So the list with the two examples would look like this:  

Identifier | Address type
--------- | -------------
... | ...
1337 | Zcash t-address
1338 | Zcash z-address
... | ...
1423 | Lisk
1424 | Lisk delegate
... | ...

**Comment by ThatBrianDude** [comment]
I prefer @shilch 's solution since it might be difficult to stay consistent while coming up with strings for identifiers especially when there are different address types.

**Comment by shilch** [comment]
@ThatBrianDude In Discord we discussed sending the pure address data instead of the human-readable address encoding, i.e. for Nano this means sending the public key instead of the human-readable format (xrb_ / nano_) and for Bitcoin Cash a public key hash. This is a measure to improve wallet compatibility in case a cryptocurrency introduces a new address format that does not change the underlying data that is transferred with it (e.g. the cashaddr format in Bitcoin Cash).  

Taken from the Discord discussion:

> Here's a picture to describe what I mean: Currently, the CAP server sends an address format (red circle) instead of the actual address data (green circle). That's not much of an issue if the address formats don't change. However, if they change (they already did for NANO and BCH; will probably happen to other coins as well), old wallets will have compatibility issue when they receive an address format that they don't know.
> ![](https://cdn.discordapp.com/attachments/470710515975323652/471059794099437599/change.png)

I don't think that it would change the way a wallet dev has to deal with the data much. In fact, from a programming architectural point of view it's a clear separation between data layer and interface layer.  

So the table would look like this:  

| ID | Distributed Ledger / P2P Network | Type |
| -- | ---------------------------------- | ----- |
| 0  | Bitcoin Cash                                     | Bitcoin |
| 1  | Nano / RaiBlocks                               | Nano |
| 2 | BitMessage                                        | BitMessage |
| ... | ... | ... |
| X | Dogecoin                                           | Bitcoin |
| ... | ... | ... |

**Types**  

**Bitcoin:**

| Type | Description |
| ----- | ------------- |
| 0 | Encodes a public key hash (P2PKH) |
| 1 | Encodes a script hash (P2SH) |

**Nano:**

| Type | Description |
| ----- | ----------- |
| 0       | Encodes a public key (standard Nano address) |

**BitMessage:**
...

Please note that we can just reuse type 'Bitcoin' for all Bitcoin-based distributed ledgers. We can further inherit from these types, e.g. create a 'SegWit' type for Bitcoin-based ledgers that have implemented SegWit. Or in the case of Zcash we no longer have two identifiers but one that can either be a t-address or z-address, that means we would create a 'Zerocash' type that inherits from the 'Bitcoin' type.  
At first glance this looks like too much of an overhead. However, a wallet developer does not need to implement every single type but only the ones that are needed for the wallet (e.g. a Nano wallet will only need to implement the Nano type and not the Bitcoin type).  

To give an example of how a return from a CAP might look like:  
```js
{
    "error": {
        "code": 0,
        "message": "success"
    },
    "data": [
        {
            "type": 0,               // this is a Bitcoin Cash address
            "address": {
                "type": 0,           // this is a P2PKH address
                "data": "YukHsVy/J9VCU5nr9vD7UOu4jxg=" // public key hash in base64
            },
            "label": "My Bitcoin Cash address",
            "extensions": {      // extension data appears here (e.g. dns and pgp signatures)
                "dnssig": "...",
                "pgpsig": "..."
            }
        },
        {
            "type": 0,               // this is a Bitcoin Cash address
            "address": {
                "type": 1,           // this is a P2SH address
                "data": "GafYaQMjaP0fHibl5zpK0OR0lg4=" // script hash in base64
            },
            "label": "My MultiSig wallet",
            "extensions": {
                "dnssig": "..."
            }
        },
        {
            "type": 1,               // this is a Nano address
            "address": {
                "type": 0,           // this is a standard public key address
                "data": "XKdD14CTd6BNYerDzfkqFDilogkaqdbZpaYq6EqxuQ8=" // public key in base64
            },
            "label": "My NANO address",
            "extensions": {
                "dnssig": "...",
                "pgpsig": "..."
            }
        }
    ],
    "extensions": {
        "profile": {
            "name": "John Doe",
            "image_url": "https://..."
        }
    }
}
```

**Comment by ThatBrianDude** [comment]
As further discussed on discord we came to the conclusion there is no need for labels.

Having stripped the response down to the bare minimum there is one more question to be asked and that is:

Do we really need different types for currencies/tokens or should each subtype get its own top level id? 

## Tokens
| ID        | Token  |
| ------------- |:-------------:| 
| 0     | zcash z-address | 
| 1      |  zcash t-address |
| ...| ... |

### HTTP JSON Response

```json
{
  "error": {
        "code": 0,
        "message": "success"
    },
    
  "data": {
      "0": {
          "address": "YukHsVy/J9VCU5nr9vD7UOu4jxg=",
          "extensions": {
            "dnssig": "..."
          } 
      },
      "1": {
          "address": "XKdD14CTd6BNYerDzfkqFDilogkaqdbZpaYq6Eqxu="
      }
  }
}
```

## VS

### Tokens
| ID    | Token  |
| ------------- |:-------------:| 
| 0     | zcash | 
| 1      |  btc |
| ...| ... |

### zcash
| Address-Type | Description  |
| ------------- |:-------------:| 
| 0     | z-address | 
| 1      |  t-address |
| ...| ... |

### HTTP JSON Response

```json
{
  "error": {
        "code": 0,
        "message": "success"
    },
    
  "data": {
      "0": {
          "addresses": [
              "YukHsVy/J9VCU5nr9vD7UOu4jxg=",
              "GafYaQMjaP0fHibl5zpK0OR0lg4="
          ],
          "extensions": {
            "dnssig": "..."
          } 
      },
      "1": {
          "addresses": [ "XKdD14CTd6BNYerDzfkqFDilogkaqdbZpaYq6EqxuQ8="
          ]
      }
  }
}
```

IMO having just one level will surely simplify things to the bear minimum.

**Comment by shilch** [comment]
After some thought I would do a mix of the possible solutions:  

### Supported Ledgers and Networks

| ID |  Distributed Ledger / P2P Network | Type |
| -- | ---------------------------------- | ----- |
| 0  | Bitcoin Cash                                      | Bitcoin |
| 1  | Nano / RaiBlocks                               | Nano |
| 2 | Zcash (transparent)                          | Zerocash t |
| 3 | Zcash (shielded)                               | Zerocash z |
| 4 | Ethereum                                           | Ethereum |
| 5 | Ethereum Classic                              | Ethereum |
| 6 | Bitcoin (Bitcoin)                                | Bitcoin |
| 7 | Bitcoin (SegWit)                                | SegWit |
| 8 | Litecoin (Bitcoin)                               | Bitcoin |
| 9 | Litecoin (SegWit)                               | SegWit |

That means that we assign every ledger an identifier. For most cryptocurrencies this is only one but there are a few with two (e.g. Zcash as it has a public and a private ledger). I would consider SegWit to be a separate ledger as well so this system is compatible with wallets that don't support SegWit.

### **Types**

**Bitcoin:**

| Type | Description | Data |
| ----- | -----------  | ----- |
| 0       | P2PKH address | public key hash |
| 1        | P2SH address   | script hash |

**Nano:**

| Type | Description | Data |
| ----- | -----------  | ----- |
| 0       | Standard address | public key |

**SegWit:**

| Type | Description | Data |
| ----- | -----------  | ----- |
| 0       | P2WPKH address | public key hash |
| 1        | P2WSH address   | script hash |

So, a typical response would look like this:  

```json
{
  "error": {
        "code": 0,
        "message": "success"
    },
    
  "data": {
      "0": {
          "type": 0,
          "address": "YukHsVy/J9VCU5nr9vD7UOu4jxg=",
          "extensions": {
            "dnssig": "..."
          } 
      },
      "1": {
          "type": 0,
          "address": "XKdD14CTd6BNYerDzfkqFDilogkaqdbZpaYq6Eqxu="
      }
  }
}
```

**Comment by lane-c-wagner** [comment]
I disagree, I think separating by chain is not a separation we care about. We care about a separation of wallet types. Remember, the server just serves wallets, it does no actual transactions. This is what I would do:

| CoinID | Name|
| ----- | -----------  |
| 0       | Bitcoin |
| 1       | Bitcoin Cash |
| 2       | Nano |

With this table I could then query to get the supported coins of my recipient: (I like using the word "coin even though some are tokens, or securities, or whatever. It keeps things simple and sexy)

GET /coin/{username}
200 OK
```json
{
	"message": "success",
	"coins": [
		0,
		2,
		3
	]
}
```

Once I know the coins that this user's alias supports I query again:

GET /address/{CoinID}/{username}
200 OK
```javacript
{
	"message": "success",
	"0": {
		"address": "YukHsVy/J9VCU5nr9vD7UOu4jxg=",
		"extensions": {
			"dnssig": "..."
		}
	}
}
```

The nice thing about doing it this way is that it flows well with the UI, not returning more data than necessary. I type the recipients alias in, the wallet then lets me know which currency options I have for sending. I tap a currency, my wallet gets the actual address and done!

**Comment by shilch** [comment]
When the server returns something like  
```json
{
	"message": "success",
	"0": {
		"address": "YukHsVy/J9VCU5nr9vD7UOu4jxg=",
		"extensions": {
			"dnssig": "..."
		}
	}
}
```

There is no way for the wallet software to find out which of the 4 Bitcoin/SegWit address type this is.

**Comment by lane-c-wagner** [comment]
Sorry, I left out address type. Edited.

**Comment by shilch** [comment]
But this does not work with non-SegWit wallets

**Comment by ThatBrianDude** [comment]
That would be optimized for multi crypto wallets but not simple single-crypto wallets...

**Comment by lane-c-wagner** [comment]
In conclusion we decided to go with a ledger_id for each ledger so we won't have duplicate tickers. Most coins will only have one ledger, but some with have 2 so this is necessary (Zcash z addresses, Bitcoin Segwit). I'm closing the issue for now.
